---
title: "Lecture 24: Neyman-Pearson and Likelihood ratio tests"
format: 
  revealjs:
    theme: theme.scss
editor: source
editor_options: 
  chunk_output_type: console
---


## Recap: Neyman-Pearson test

Let $X_1,...,X_n$ be a sample from a distribution with probability function $f$, and parameter $\theta$. To test
$$H_0: \theta = \theta_0 \hspace{1cm} H_A: \theta = \theta_1,$$
the Neyman-Pearson test rejects $H_0$ when
$$\frac{L(\theta_1 | {\bf X})}{L(\theta_0 | {\bf X})} > k,$$
where $k$ is chosen so that $\beta(\theta_0) = \alpha$.


## Warm-up

Let $X_1,...,X_n \overset{iid}{\sim} Poisson(\lambda)$. We wish to test $H_0: \lambda = \lambda_0$ vs. $H_A: \lambda = \lambda_1$, where $\lambda_1 > \lambda_0$. Find a most powerful test for these hypotheses (that is, determine a rejection region such that the test has a desired type I error rate $\alpha$).

## Recap: Neyman-Pearson lemma

The Neyman-Pearson test is a *uniformly most power* level $\alpha$ test of $H_0: \theta = \theta_0$ vs. $H_A: \theta = \theta_1$.

## Another question

Let $X_1,...,X_n \overset{iid}{\sim} Poisson(\lambda)$. We wish to test $H_0: \lambda = \lambda_0$ vs. $H_A: \lambda \neq \lambda_0$.

## Likelihood ratio tests

## Back to the Poisson example

Let $X_1,...,X_n \overset{iid}{\sim} Poisson(\lambda)$. We wish to test $H_0: \lambda = \lambda_0$ vs. $H_A: \lambda \neq \lambda_0$.

## Asymptotics of the LRT

